### ISSUE TITLE
Share Grafana setup/dashboard

### ISSUE THREAD

**Issue by robbrad** [ntalekt/homeassistant#41]
That Grafana dashboard is amazing - how did you do it? how did you have it checking system processes?

Thanks
Rob

**Comment by ntalekt** [comment]
Sharing the dashboard won't be much help since it's customized to my environment. This article by Phil Hawthorne was very helpful: https://philhawthorne.com/getting-started-with-grafana-influxdb-for-home-assistant/

I used command_line [binary_sensors](https://www.home-assistant.io/components/binary_sensor/) to check local or remote processes via shell script:

**Local process**
```
  - platform: command_line
    name: NGINX Status
    command: "/home/pi/web_check.sh"
    device_class: connectivity
    payload_on: "Up"
    payload_off: "Down"
```

**Remote process**
```
  - platform: command_line
    name: Deluge Process
    command: 'ssh pi@<ip address> "./check_deluged.sh"'
    device_class: connectivity
    payload_on: "Up"
    payload_off: "Down"
```

**Shell script**
```
#! /bin/bash

if curl -s --head  --request GET https://<frontend URL> | grep "200 OK" > /dev/null; then
   echo "Up"
else
   echo "Down"
fi
```
